version: "2"
services:
 quiz:
   image: quizart-ui:0.1.0
   build: './web'
   expose:
     - 8081
   ports:
     - 8081:8081
   environment:
      NEO4j_DRIVER: 'bolt://localhost'
      REDIS_HOST: '172.23.238.251'
      REDIS_PORT: 6379
      EXPRESS_PORT: 8081
 gamecontroller:
    build: ./game-controller
    image: game-controller
    environment:
      REDIS_HOST: "172.23.238.251"
      REDIS_PORT: 6379
 provisioner:
    build: './game-provisioner'
    image: game-provisioner
    environment:
      REDIS_HOST: "172.23.238.251"
      REDIS_PORT: 6379
      NEO4j_DRIVER: "bolt://localhost"
 cluegenerator:
   build: './clues-generator'
   image: clue_generator
   environment:
     NEO4j_DRIVER: 'bolt://localhost'
     REDIS_HOST: "172.23.238.251"
     REDIS_PORT: 6379
