version: "2"
services:
 quiz:
   image: quizart-ui:0.1.0
   build: './web'
   expose:
     - 8081
   ports:
     - 8081:8081
   links:
     - db
     - redis
     - neo4j
   depends_on:
     - redis
     - db
     - neo4j
   environment:
      NEO4j_DRIVER: 'bolt://neo4j'
      MONGO_URL: 'mongodb://db/test'
      REDIS_HOSTNAME: 'redis'
      REDIS_PORT: 6379
      EXPRESS_PORT: 8081
 provisioner:
    build: './game-provisioner'
    image: game-provisioner
    links:
      - redis
    depends_on:
      - redis
    environment:
      REDIS_HOSTNAME: "redis"
      REDIS_PORT: 6379
 cluegenerator:
   build: './clues-generator'
   image: clue_generator
   links:
     - redis
   depends_on:
     - redis
     - neo4j
   environment:
     NEO4j_DRIVER: 'bolt://neo4j'
     REDIS_HOST: "redis"
     REDIS_PORT: 6379
 neo4j:
   image: neo4j
   ports:
     - 7474:7474
     - 7687:7687
   volumes:
     - $HOME/neo4j/data:/data
 db:
   image: khezen/mongo
   ports:
     - 27017:27017
 redis:
   image: redis:3.0.7
   ports:
     - 6379:6379
